export const LANGUAGES = [
  { code: 'en', name: 'Inglés' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Francés' },
  { code: 'de', name: 'Alemán' },
  { code: 'it', name: 'Italiano' },
  { code: 'pt', name: 'Portugués' },
  { code: 'ru', name: 'Ruso' },
  { code: 'zh', name: 'Chino' },
  { code: 'ja', name: 'Japonés' },
  { code: 'ar', name: 'Árabe' },
  { code: 'ko', name: 'Coreano' },
  { code: 'nl', name: 'Neerlandés' },
  { code: 'pl', name: 'Polaco' },
  { code: 'sv', name: 'Sueco' },
  { code: 'tr', name: 'Turco' },
  { code: 'hi', name: 'Hindi' },
  { code: 'bn', name: 'Bengalí' },
  { code: 'id', name: 'Indonesio' },
  { code: 'vi', name: 'Vietnamita' },
  { code: 'he', name: 'Hebreo' },
  { code: 'th', name: 'Tailandés' },
];
