services:
    hone_front_new:
        image: node:18.19.1
        user: 'root'
        container_name: 'hone_front_new'
        ports:
          - "7002:4200"
        volumes:
          - .:/app
        working_dir: /app
        networks:
            - local_net
        stdin_open: true
        tty: true
        command: npm run start -- --host 0.0.0.0 --disable-host-check
networks:
    local_net:
        name: local_net
        driver: bridge
        external: true
