services:
    hs_prestadores:
        image: node:18.19.1
        user: 'root'
        container_name: 'hs_prestadores'
        ports:
          - "7003:7003"
        volumes:
          - .:/app:rw
        working_dir: /app
        networks:
            - local_net
        stdin_open: true
        tty: true
        command: npm run start -- --host 0.0.0.0 --disable-host-check
networks:
    local_net:
        name: local_net
        driver: bridge
        external: true
